#!/usr/bin/env python3
"""Generate src/aws-exports.js from the deployed backend stack outputs.

On the Amplify Hosting rail, `amplifyPush` writes src/aws-exports.js as a
side effect. On the CodeBuild rail the backend is deployed as plain
CloudFormation, so this script reconstructs the same file from the root
stack's nested-stack outputs (AppSync endpoint, Cognito pool/client ids).

Usage: generate-aws-exports.py <root-stack-name>   (region from AWS_REGION)
"""
import json
import os
import sys

import boto3

root = sys.argv[1]
region = os.environ.get("AWS_REGION", "us-east-1")
cf = boto3.client("cloudformation", region_name=region)

outputs = {}
stacks = [root]
seen = set()
while stacks:
    name = stacks.pop()
    if name in seen:
        continue
    seen.add(name)
    desc = cf.describe_stacks(StackName=name)["Stacks"][0]
    for o in desc.get("Outputs", []) or []:
        outputs.setdefault(o["OutputKey"], o["OutputValue"])
    for page in cf.get_paginator("list_stack_resources").paginate(StackName=name):
        for r in page["StackResourceSummaries"]:
            if r["ResourceType"] == "AWS::CloudFormation::Stack" and r.get("PhysicalResourceId"):
                stacks.append(r["PhysicalResourceId"])

def pick(*keys):
    for k in keys:
        for ok, ov in outputs.items():
            if ok == k or ok.endswith(k):
                return ov
    return ""

exports = {
    "aws_project_region": region,
    "aws_appsync_graphqlEndpoint": pick("GraphQLAPIEndpointOutput"),
    "aws_appsync_region": region,
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": pick("IdentityPoolId"),
    "aws_cognito_region": region,
    "aws_user_pools_id": pick("UserPoolId"),
    "aws_user_pools_web_client_id": pick("AppClientIDWeb"),
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": ["EMAIL"],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": ["SMS"],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [],
    },
    "aws_cognito_verification_mechanisms": ["EMAIL"],
}

missing = [k for k in ("aws_appsync_graphqlEndpoint", "aws_user_pools_id") if not exports[k]]
if missing:
    print(f"WARNING: missing outputs for {missing} — generated file may be incomplete")

body = ("/* eslint-disable */\n"
        "// Generated by deployment/generate-aws-exports.py from the deployed\n"
        "// backend stack outputs (CodeBuild rail equivalent of amplifyPush's\n"
        "// aws-exports side effect).\n"
        f"const awsmobile = {json.dumps(exports, indent=2)};\n\n"
        "export default awsmobile;\n")
open("src/aws-exports.js", "w").write(body)
print(f"src/aws-exports.js written ({len(seen)} stacks scanned, "
      f"endpoint={'set' if exports['aws_appsync_graphqlEndpoint'] else 'MISSING'})")
